# Generated by Django 3.2.9 on 2021-11-27 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="passenger",
            name="identification_number",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="passenger",
            name="registered_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
